apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tenants
  namespace: {{ .Values.namespace }}
spec:
  description: ETX tenant application plane
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
    - namespace: '*'
      name: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
