{{- if .Values.sso.clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: etx-gitops-oidc-secret
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: etx-gitops-oidc-secret
    app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
  clientSecret: {{ .Values.sso.clientSecret | quote }}
{{- end }}
