{{- if and .Values.repo.url .Values.repo.password }}
apiVersion: v1
kind: Secret
metadata:
  name: etx-platform-bootstrap-repo
  namespace: {{ .Values.namespace }}
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: {{ .Values.repo.url | quote }}
  username: {{ .Values.repo.username | quote }}
  password: {{ .Values.repo.password | quote }}
{{- end }}
