apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-seed
  namespace: {{ .Values.gitlab.namespace | default "gitlab" }}
  labels:
    app.kubernetes.io/name: gitlab-seed
    app.kubernetes.io/part-of: etx-lab-platform
