{{- if .Values.instance.automationUser.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-automation-user
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: gitlab-automation-user
    app.kubernetes.io/part-of: gitlab-etx-lab
type: Opaque
stringData:
  username: {{ .Values.instance.automationUser.username }}
  password: {{ .Values.instance.automationUser.password }}
  email: {{ .Values.instance.automationUser.email }}
  displayName: {{ .Values.instance.automationUser.displayName }}
  canCreateGroup: {{ ternary "true" "false" .Values.instance.automationUser.canCreateGroup | quote }}
{{- end }}
