{{- if .Values.instance.oidc.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-oidc-secret
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: gitlab-oidc
    app.kubernetes.io/part-of: gitlab-etx-lab
type: Opaque
stringData:
  provider: |
    name: openid_connect
    label: ETX Lab SSO
    args:
      name: openid_connect
      scope:
        - openid
      response_type: code
      issuer: {{ .Values.instance.oidc.issuer }}
      discovery: true
      client_auth_method: post
      uid_field: preferred_username
      send_nonce: false
      pkce: false
      client_options:
        identifier: {{ .Values.instance.oidc.clientId }}
        secret: etx-lab-workshop-gitlab-secret
        redirect_uri: https://{{ .Values.instance.hostname }}.{{ .Values.deployer.domain }}/users/auth/openid_connect/callback
{{- end }}
