{{- range .Values.primaryCluster.namespaces }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ . }}
  labels:
    app.kubernetes.io/part-of: etx-lab-platform
    demo.redhat.com/platform: "true"
    etx-lab/environment: {{ . }}
{{- end }}
