apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: openshift-gitops
    app.kubernetes.io/component: gitops
    app.kubernetes.io/part-of: etx-lab-infrastructure
    demo.redhat.com/infra: "true"
