apiVersion: v1
kind: Secret
metadata:
  name: quay-config-bundle
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: quay-config-bundle
    app.kubernetes.io/part-of: etx-lab-platform
type: Opaque
stringData:
  config.yaml: |
    FEATURE_USER_INITIALIZE: true
    BROWSER_API_CALLS_XHR_ONLY: false
    SUPER_USERS:
      - {{ .Values.superuser.username }}
    FEATURE_USER_CREATION: true
    FEATURE_ANONYMOUS_ACCESS: false
    FEATURE_DIRECT_LOGIN: true
    {{- if .Values.instance.oidc.enabled }}
    AUTHENTICATION_TYPE: OIDC
    OIDC_LOGIN_CONFIG:
      OIDC_SERVER: {{ .Values.instance.oidc.issuer }}/
      CLIENT_ID: {{ .Values.instance.oidc.clientId }}
      CLIENT_SECRET: etx-lab-workshop-quay-secret
      SERVICE_NAME: Keycloak
      VERIFIED_EMAIL_CLAIM_NAME: email
      LOGIN_SCOPES:
        - openid
    {{- end }}
    DEFAULT_TAG_EXPIRATION: 2w
    FEATURE_BUILD_SUPPORT: false
    FEATURE_QUOTA_MANAGEMENT: true
    FEATURE_PROXY_CACHE: true
    FEATURE_TEAM_SYNCING: false
    TEAM_RESYNC_STALE_TIME: 60m
    FEATURE_NONSUPERUSER_TEAM_SYNCING_SETUP: false
    PREFERRED_URL_SCHEME: https
    SERVER_HOSTNAME: {{ .Values.instance.hostname }}
