apiVersion: v1
kind: Secret
metadata:
  name: etx-keycloak-db-secret
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: etx-keycloak-db-secret
    app.kubernetes.io/instance: etx-keycloak
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: etx-lab-platform
type: Opaque
stringData:
  username: keycloak
  password: keycloak
  database: keycloak
  host: etx-keycloak-postgres
  port: "5432"
